name: build

on:
  push:
  pull_request:
  schedule:
    - cron: '0 15 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ '12.16', '13.7', '16.0' ]
        test: [
          'test',
        ]
    name: "v${{ matrix.node }}: ${{ matrix.test }}"
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2-beta
        with:
          node-version: ${{ matrix.node }}
      - run: yarn install
      - run: yarn run ${{matrix.test}}
